SET SERVEROUTPUT ON;
CREATE TABLE TRABAJADOR(ID_SEGURO INTEGER PRIMARY KEY,NOMBRE VARCHAR2(25),EDAD INTEGER);


CREATE TABLE NOMINA(ID_NOMINA INTEGER,ID_SEGURO INTEGER,SUELDO_BASE FLOAT,HORAS_LABORADAS INTEGER,FECHA_PAGO DATE,
CONSTRAINT PK_ID_NOMINA PRIMARY KEY (ID_NOMINA),CONSTRAINT FK1_ID_SEGURO FOREIGN KEY (ID_SEGURO) REFERENCES TRABAJADOR (ID_SEGURO));

CREATE SEQUENCE SEC_NOMINA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE OR REPLACE PROCEDURE GUARDAR_NOMINA(MY_ID_NOMINA OUT INTEGER,MY_ID_SEGURO IN INTEGER, MY_SUELDO_BASE IN INTEGER) AS
BEGIN
SELECT SEC_NOMINA.NEXTVAL INTO MY_ID_NOMINA FROM DUAL;
INSERT INTO NOMINA (ID_NOMINA,ID_SEGURO, SUELDO_BASE)
VALUES (MY_ID_NOMINA,MY_ID_SEGURO,MY_SUELDO_BASE);
END;
/
--PROCEDIMIENTO DONDE INVOCAS EL PROCEDIMIENTO DE NOMINA
CREATE OR REPLACE PROCEDURE GENERAR_TRABAJADOR(MY_ID_SEGURO IN INTEGER,MY_NOMBRE IN VARCHAR2,MY_EDAD IN INTEGER,MY_ID_NOMINA OUT INTEGER,
MY_SUELDO_BASE IN FLOAT) AS 
BEGIN
INSERT INTO TRABAJADOR VALUES (MY_ID_SEGURO,MY_NOMBRE,MY_EDAD);
GUARDAR_NOMINA(MY_ID_NOMINA, MY_ID_SEGURO, MY_SUELDO_BASE);
END;
/

DECLARE
VALOR INTEGER;
BEGIN
GENERAR_TRABAJADOR(1,'ANA',28,VALOR,6000);
 GENERAR_TRABAJADOR(2,'PEDRO',40,VALOR,8000);
  GENERAR_TRABAJADOR(3,'JUAN',35,VALOR,7000);
   GENERAR_TRABAJADOR(4,'KARLA',41,VALOR,10000);
   
   END;
   /
   
   SELECT * FROM NOMINA;
