set serveroutput on;
--RECAPITULANDO LO QUE ES UN BLOQUE PL SQL;
DECLARE
nombre varchar2(20):='Jose Armando';
BEGIN
DBMS_OUTPUT.PUT_LINE('BUENAS NOCHES '||nombre);
END;
/

DECLARE 
EDAD INTEGER:=21;
DIAS INTEGER;
ESTATUS VARCHAR2(12);
BEGIN
DIAS:=EDAD*365;
IF dias >10000 then
  ESTATUS:='VIEJO';
ELSE
  ESTATUS:='JOVEN';
  END IF;
  
DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIASES' || DIAS || 'ESTATUS:' || ESTATUS);
END;
/


--VREMOS NUESTRO PRIMER PROCEDIMIENTO ALMACENADO
CREATE OR REPLACE PROCEDURE saludar(mensaje IN varchar2)
AS
BEGIN
DBMS_OUTPUT.PUT_LINE('HOLA BUENAS NOCHE'||mensaje);
END;
/


--ejecutamos el procedimiento
exec saludar('armando precioso');



--generamos la secuencia

CREATE SEQUENCE SEC_PERSONA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


--GENERAMOS LA TABLA
CREATE TABLE PERSONA(ID_PERSONA INTEGER, NOMBRE VARCHAR2(20),EDAD INTEGER, CONSTRAINT PK_ID_PERSONA PRIMARY KEY (ID_PERSONA));
